In [1]:
### Preprocessing data
from sklearn import preprocessing
import numpy as np

In [2]:
X_train = np.array([[ 1., -1.,  2.],
...                     [ 2.,  0.,  0.],
...                     [ 0.,  1., -1.]])

In [3]:
X_train.shape, X_train

((3, 3),
 array([[ 1., -1.,  2.],
        [ 2.,  0.,  0.],
        [ 0.,  1., -1.]]))

In [4]:
X_scaled = preprocessing.scale(X_train)
X_scaled.mean(),X_scaled.std(),X_scaled.var(),X_scaled

(4.9343245538895844e-17,
 1.0,
 1.0,
 array([[ 0.        , -1.22474487,  1.33630621],
        [ 1.22474487,  0.        , -0.26726124],
        [-1.22474487,  1.22474487, -1.06904497]]))

In [5]:
# example of standardization
from sklearn.preprocessing import StandardScaler
from numpy import array

In [6]:
# define dataset
data = [x for x in range(1, 10)]
data = array(data).reshape(len(data), 1)
print(data)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [7]:
# fit transform
transformer = StandardScaler()
transformer.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [8]:
# difference transform
transformed = transformer.transform(data)
print(transformed)

[[-1.54919334]
 [-1.161895  ]
 [-0.77459667]
 [-0.38729833]
 [ 0.        ]
 [ 0.38729833]
 [ 0.77459667]
 [ 1.161895  ]
 [ 1.54919334]]


In [9]:
# invert difference
inverted = transformer.inverse_transform(transformed)
print(inverted)

[[1.]
 [2.]
 [3.]
 [4.]
 [5.]
 [6.]
 [7.]
 [8.]
 [9.]]


In [10]:
X_train_transformed = transformer.transform(X_train)

In [18]:
import re
word = "Work"
input_string = "HomB-Work-Home-Work-HomE"
count = sum(1 for _ in re.finditer(r'\b%s\b' % re.escape(word), input_string))
count

2